language: node_js
node_js:
  - "node"

cache: yarn

script:
  - yarn run lint
  - yarn run test
  - yarn run e2e.update
  - yarn run e2e

before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

after_success:
  - yarn global add codecov && codecov
