export default {
  input: 'dist/index.js',
  name: 'inputflow',
  sourcemap: true,
  output: {
    file: 'dist/bundles/inputflow.umd.js',
    format: 'umd',
  },
  globals: {
    '@angular/core': 'ng.core',
    'rxjs/Observable': 'Rx',
    'rxjs/Subject': 'Rx',
    'rxjs/observable/merge': 'Rx.Observable',
    'rxjs/observable/timer': 'Rx.Observable',
    'rxjs/operators/debounce': 'Rx.operators',
    'rxjs/operators/distinct': 'Rx.operators',
    'rxjs/operators/map': 'Rx.operators',
    'rxjs/operators/mapTo': 'Rx.operators',
    'rxjs/operators/merge': 'Rx.operators',
    'rxjs/operators/mergeMap': 'Rx.operators',
    'rxjs/operators/toArray': 'Rx.operators',
    'rxjs/operators/window': 'Rx.operators',
    'rxjs/operators/withLatestFrom': 'Rx.operators',
  },
};
